###############################################################
#  Generated by:      Cadence Innovus 22.15-s091_1
#  OS:                Linux x86_64(Host ID micron4.eng.tau.ac.il)
#  Generated on:      Wed Aug 26 05:12:09 2026
#  Design:            top
#  Command:           create_ccopt_clock_tree_spec -file ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Through pins for multi output cells.
set_ccopt_property trace_through_to -pin I5/I1/PAD C

# Clocks present at pin clk
#   clk (period 1.042ns) in timing_config TypCM([/project/verif/users/marianajjar/ws/spline_3_1_rerun/innovus/datain/top_interpolator_dac.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner SlowDC -late -clock_tree clk 0.200
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 1.04167

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:TypCM (sdc /project/verif/users/marianajjar/ws/spline_3_1_rerun/innovus/datain/top_interpolator_dac.sdc)
create_ccopt_skew_group -name clk/TypCM -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/TypCM true
set_ccopt_property extracted_from_clock_name -skew_group clk/TypCM clk
set_ccopt_property extracted_from_constraint_mode_names -skew_group clk/TypCM {TypCM  }
set_ccopt_property extracted_from_delay_corners -skew_group clk/TypCM {SlowDC FastDC}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

